title: Brenda Morales
logo: "C:\Users\wwwma\Downloads\A professional LinkedIn photo is a crucial element of your online presence, as it serves as a first impression for potential employers, colleagues, and professional contacts. To make the most of y (1).png"
# description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
